// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMKYmlMPosaTMFobSaY4PtioT0ddDlvi0',
    appId: '1:920723721120:web:6fba7f840084f3f9ccf2c5',
    messagingSenderId: '920723721120',
    projectId: 'zoozoowin-a8a38',
    authDomain: 'zoozoowin-a8a38.firebaseapp.com',
    storageBucket: 'zoozoowin-a8a38.appspot.com',
    measurementId: 'G-2MP48CSW58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBocr97sxhptrFhllzOAOL04hywAIGYeCY',
    appId: '1:920723721120:android:e888b3871f168c0accf2c5',
    messagingSenderId: '920723721120',
    projectId: 'zoozoowin-a8a38',
    storageBucket: 'zoozoowin-a8a38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD34gnIeuxEc8sYRB70wukPe7tKQ5AdXtM',
    appId: '1:920723721120:ios:b9bd2525e80f14d2ccf2c5',
    messagingSenderId: '920723721120',
    projectId: 'zoozoowin-a8a38',
    storageBucket: 'zoozoowin-a8a38.appspot.com',
    iosBundleId: 'com.example.zoozoowin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD34gnIeuxEc8sYRB70wukPe7tKQ5AdXtM',
    appId: '1:920723721120:ios:b9bd2525e80f14d2ccf2c5',
    messagingSenderId: '920723721120',
    projectId: 'zoozoowin-a8a38',
    storageBucket: 'zoozoowin-a8a38.appspot.com',
    iosBundleId: 'com.example.zoozoowin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMKYmlMPosaTMFobSaY4PtioT0ddDlvi0',
    appId: '1:920723721120:web:2b6e0ad07875a52accf2c5',
    messagingSenderId: '920723721120',
    projectId: 'zoozoowin-a8a38',
    authDomain: 'zoozoowin-a8a38.firebaseapp.com',
    storageBucket: 'zoozoowin-a8a38.appspot.com',
    measurementId: 'G-FKJ3J3WZ9V',
  );
}
